package com.sopanha.translatorapp.utils

data class Language(val name: String, val code: String)

object Languages {
    val all = listOf(
        Language("Auto Detect", "auto"),
        Language("Afrikaans", "af"),
        Language("Albanian", "sq"),
        Language("Arabic", "ar"),
        Language("Armenian", "hy"),
        Language("Azerbaijani", "az"),
        Language("Basque", "eu"),
        Language("Belarusian", "be"),
        Language("Bengali", "bn"),
        Language("Bosnian", "bs"),
        Language("Bulgarian", "bg"),
        Language("Catalan", "ca"),
        Language("Cebuano", "ceb"),
        Language("Chinese (Simplified)", "zh-CN"),
        Language("Chinese (Traditional)", "zh-TW"),
        Language("Croatian", "hr"),
        Language("Czech", "cs"),
        Language("Danish", "da"),
        Language("Dutch", "nl"),
        Language("English", "en"),
        Language("Esperanto", "eo"),
        Language("Estonian", "et"),
        Language("Finnish", "fi"),
        Language("French", "fr"),
        Language("Galician", "gl"),
        Language("Georgian", "ka"),
        Language("German", "de"),
        Language("Greek", "el"),
        Language("Gujarati", "gu"),
        Language("Haitian Creole", "ht"),
        Language("Hebrew", "he"),
        Language("Hindi", "hi"),
        Language("Hungarian", "hu"),
        Language("Icelandic", "is"),
        Language("Indonesian", "id"),
        Language("Irish", "ga"),
        Language("Italian", "it"),
        Language("Japanese", "ja"),
        Language("Javanese", "jv"),
        Language("Kannada", "kn"),
        Language("Khmer", "km"),
        Language("Korean", "ko"),
        Language("Latin", "la"),
        Language("Latvian", "lv"),
        Language("Lithuanian", "lt"),
        Language("Macedonian", "mk"),
        Language("Malay", "ms"),
        Language("Maltese", "mt"),
        Language("Maori", "mi"),
        Language("Marathi", "mr"),
        Language("Mongolian", "mn"),
        Language("Nepali", "ne"),
        Language("Norwegian", "no"),
        Language("Persian", "fa"),
        Language("Polish", "pl"),
        Language("Portuguese", "pt"),
        Language("Punjabi", "pa"),
        Language("Romanian", "ro"),
        Language("Russian", "ru"),
        Language("Serbian", "sr"),
        Language("Sinhala", "si"),
        Language("Slovak", "sk"),
        Language("Slovenian", "sl"),
        Language("Somali", "so"),
        Language("Spanish", "es"),
        Language("Sundanese", "su"),
        Language("Swahili", "sw"),
        Language("Swedish", "sv"),
        Language("Tagalog", "tl"),
        Language("Tamil", "ta"),
        Language("Telugu", "te"),
        Language("Thai", "th"),
        Language("Turkish", "tr"),
        Language("Ukrainian", "uk"),
        Language("Urdu", "ur"),
        Language("Uzbek", "uz"),
        Language("Vietnamese", "vi"),
        Language("Welsh", "cy"),
        Language("Xhosa", "xh"),
        Language("Yiddish", "yi"),
        Language("Yoruba", "yo"),
        Language("Zulu", "zu")
    )

    val sourceLanguages = all
    val targetLanguages = all.filter { it.code != "auto" }

    fun names(): Array<String> = all.map { it.name }.toTypedArray()
    fun targetNames(): Array<String> = targetLanguages.map { it.name }.toTypedArray()
    fun codeByName(name: String) = all.find { it.name == name }?.code ?: "auto"
    fun targetIndexOf(code: String) = targetLanguages.indexOfFirst { it.code == code }.takeIf { it >= 0 } ?: 0
    fun sourceIndexOf(code: String) = all.indexOfFirst { it.code == code }.takeIf { it >= 0 } ?: 0
}
